title: LPDS # your name (or website title) here
logo: "/images/lpds-logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Laboratório de Processamento Diginal de Sinais 
  <br><br>
  Universidade Federal de Santa Catarina 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
